/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CampfirePanel: typeof import('./components/campfire/CampfirePanel.vue')['default']
    CardView: typeof import('./components/common/CardView.vue')['default']
    ConsolePanel: typeof import('./components/console/ConsolePanel.vue')['default']
    EnemyView: typeof import('./components/common/EnemyView.vue')['default']
    EventPanel: typeof import('./components/event/EventPanel.vue')['default']
    RewardPanel: typeof import('./components/reward/RewardPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopPanel: typeof import('./components/shop/ShopPanel.vue')['default']
  }
}
